# -*- coding: utf-8 -*-
"""Dashboard_Netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmkHRGDI9rEmMgQjr0tBmlxv0mxj2POU
"""

# Add filters
type_filter = st.sidebar.multiselect(
    "Select Content Type:",
    options=df['type'].dropna().unique(),
    default=df['type'].dropna().unique()
)

country_filter = st.sidebar.multiselect(
    "Select Country:",
    options=df['country'].dropna().unique(),
    default=df['country'].dropna().unique()
)

year_min = int(df['release_year'].min())
year_max = int(df['release_year'].max())
year_range = st.sidebar.slider(
    "Select Release Year Range:",
    min_value=year_min,
    max_value=year_max,
    value=(year_min, year_max)
)

# Apply filters to the dataframe
df_filtered = df[
    (df['type'].isin(type_filter)) &
    (df['country'].isin(country_filter)) &
    (df['release_year'].between(year_range[0], year_range[1]))
]
